version: '3.9'

services:
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
  
  db:
    image: postgres:15.1-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authServer
    ports:
      - "5432:5432"

  webapp:
    build:
      context: "."
      dockerfile: Dockerfile.backend
    command: "go run mai.go"
    ports:
      - 3001:3001
    depends_on:
      - db

  
