services:
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
      
  db:
    image: postgres:bullseye
    volumes:
      - type: bind
        source: ./db-init
        target: /docker-entrypoint-initdb.d
        read_only: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: "pg_isready -h db -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
      interval: 5s
      start_period: 45s
    ports:
      - "5432:5432"